version: '3'

services:
  unicDb:
    image: 'postgres:latest'
    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: unicDb
